export const races = {
	beastmen: 'Beastmen',
	bretonnia: 'Bretonnia',
	daemonsOfChaos: 'Daemons of Chaos',
	darkElves: 'Dark Elves',
	dwarfs: 'Dwarfs',
	theEmpire: 'The Empire',
	grandCathay: 'Grand Cathay',
	greenskins: 'Greenskins',
	highElves: 'High Elves',
	khorne: 'Khorne',
	kislev: 'Kislev',
	lizardmen: 'Lizardmen',
	norsca: 'Norsca',
	nurgle: 'Nurgle',
	orgreKingdoms: 'Ogre Kingdoms',
	skaven: 'Skaven',
	slaanesh: 'Slaanesh',
	tombKings: 'Tomb Kings',
	tzeentch: 'Tzeentch',
	vampireCoast: 'Vampire Coast',
	vampireCounts: 'Vampire Counts',
	warriorsOfChaos: 'Warriors of Chaos',
	woodElves: 'Wood Elves',
}
